apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app

spec:
  replicas: 10
  selector:
    matchLabels:
      app: course-app

  #Recreate: вбиває всі pods одразу, потім створює нові. Downtime є, але немає двох версій одночасно.
  strategy:
    type: Recreate

  # RollingUpdate: замінює pods поступово. Без downtime, але дві версії можуть працювати паралельно.
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 3
  #     maxSurge: 1 
  
  template:
    metadata:
      labels:
        app: course-app
    spec:
      containers:
        - name: app
          image: shntrn/docker:hw5
          ports:
            - containerPort: 8000
          env:
            - name: APP_STORE
              value: "redis"
            - name: APP_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: course-app-config
                  key: APP_REDIS_URL
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: course-app-config
                  key: APP_MESSAGE
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "0.1"
              memory: "64Mi"
            limits:
              cpu: "0.5"
              memory: "256Mi"
